# feature.config.yml
startListening: false
# listening Queues
fetchRegisterEnabled: false
fetchDataEnabled: true
#Other Features
SNSNotification: true
CloudWatchLogging: false
SQSService: false
enableRabbitMQ: false

# Dynamic Queue Names
queueNames:
  fetchDataQueue: FetchDataQueue
  validateQueue: ValidateQueue
  fetchRegisterQueue: FetchRegisterQueue
  registerValidateQueue: RegisterValidateQueue
